# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Katarína Grešová
title: Genomics and Deep Learning PhD student
email: 514001@mail.muni.cz
#website: https://katarinagresova.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: katarinagresova
github_username:  katarinagresova
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: katarinagresova
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
#- title: Blog
#  icon: fa-brands fa-blogger #/> font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#  url: https://katarinagresova.github.io/blog/  #Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
google_analytics: G-3REVZET9R8

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello! My name is Katarína.

  I like <mark>Computer Science</mark>, <mark>Biology</mark> and everything in between. Always excited and looking for new challenges, but for now focusing on <mark>Machine learning</mark> and <mark>Genomics</mark>.

  I have Bachelor's degree in Information technology, Master's degree in Bioinformatics and Biocomputing and currently I am pursuing Doctoral studies in Genomics and Proteomics.

  I am also capable to combine my studies with work in a company and I have 3+ years experience as a Software Developer, working with <mark>Java</mark> and <mark>SQL</mark> and 5+ months experience as Machine Learning Specialist, having fun with <mark>Python</mark> and <mark>NLP</mark>.
  
  I sometimes write about thinks I do on my <a href="https://katarinagresova.github.io/blog/">blog</a>.


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Biology Crash Course
        link: https://katarinagresova.github.io/biology-crash-course/
        # link_text: Project Website
        #additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Informal notes from semi-formal biology discussions.
        description: | # this will include new lines to allow paragraphs
          You can find here notes from Biology Crash Course held in [RBP Bioinformatics lab](https://www.ceitec.eu/rbp-bioinformatics-panagiotis-alexiou/rg281). It is far from comprehensive explanation, but it might be a good starting point.
      
      - layout: top-middle
        title: Ensembl scraper
        link: https://github.com/katarinagresova/ensembl_scraper
        quote: >
          Create all functional elements datasets you ever wanted.
        description: | # this will include new lines to allow paragraphs
          Command line tool for preparing datasets of function elements sequences downloaded from Ensembl. It able to download selected data from Ensembl, do quality check, split to train-validate-test datasets and generate random negative example for each positive one.
        
      - layout: top-middle
        title: Genomic benchmarks
        link: https://github.com/ML-Bioinfo-CEITEC/genomic_benchmarks
        quote: >
          Collection of easily accessible, well curated and diverse genomics classification datasets together with current state of the art metrics.
        description: | # this will include new lines to allow paragraphs
          Finaly introducing benchmark datasets into field of genomics. Benchmarks were shown to be important in other fields as well (as imagenet or protein folding problem) since they created competition and pushed field forward. If you don't have a benchmark, then everybody is creating one for them to prove that their model is better than the others. And benchmarks also reduce the overhead of researches that want to come into this field and try different algorithms without necessary having very deep understanding of biology behind the problem.
 
  - title: Teaching # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: LF:DSIB01 Introduction to Bioinformatics (Autumn 2021) 
        link: https://is.muni.cz/course/med/autumn2021/DSIB01
        description: |
          Teaching several practical lessons focused on git, command line and NGS data preprocessing. Materials: [https://katarinagresova.github.io/DSIB01_2021/](https://katarinagresova.github.io/DSIB01_2021/).
        
        
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Masaryk University
        caption: 2020 - Present
        sub_title: PhD Genomics and Proteomics
        quote: >
          The aim of the Genomics and Proteomics program is to train top class specialist in these subjects. Students will acquire extensive and in-depth knowledge about the structure and function of the genome at all basic levels of living systems. They will deepen their knowledge and skills in basic biological disciplines, in biochemistry and proteomics and in biophysics. In addition to the theoretical principles of the discipline, students are also closely acquainted with performing basic and advanced methods used in various disciplines.
        description: |
          Research topic: Modeling Small RNA binding rules using Machine Learning

      - layout: left
        title: Brno University of Technology
        caption: 2018 - 2020
        sub_title: MSc Bioinformatics and Biocomputing
        quote: >
          Students of the branch acquire deeper knowledge in the bioinformatics and natural computing. This give them knowledge and skills base to analyse, design and verification of problems of biological databases as well as use, design, implement and accelerate algorithms for analysis of the biological data. They are able to apply natural computing algorithms (evolutionary algorithms, artificial neural networks, fuzzy systems etc.) in the complex design and optimization problems.
        description: |
          Master's Thesis: [Bacteria Classification into Taxonomic Categories Based on Properties of 16s rRNA](https://www.fit.vut.cz/study/thesis/22671/.en)

      - layout: left
        title: Brno University of Technology
        caption: 2015 - 2018
        sub_title: BSc Information Technology
        quote: >
          The aim of the Information Technology Bachelor Degree Programme is to prepare alumni who are able to act as designers, programmers, and servicemen of computer systems, digital systems, computer networks, computer-based systems and programmers and administrators of database systems and information systems.
        description: |
          Bachelor's Thesis: [Searching Semantically Annotated Texts](https://www.vutbr.cz/en/students/final-thesis/detail/114837?zp_id=114837)
          
          
          
          
          
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Proficio Marketing
        link: https://proficiodigital.com/
        # link_text: boringcompany.com
        sub_title: Machine Learning Specialist
        caption: December 2021 - Present
        quote: >
          Proficio Marketing is a digital full service agency that helps clients with performance campaigns, data and business analytics, brand building and social network management and more.
        description: | # this will include new lines to allow paragraphs
          Working as a Machine Learning Specialist for the Analytics team. 
          
          My goal is to bring additional value for customers through their data. I start with understanding the business problem, exploring the data, cleaning it, choosing the optimal machine learning algorithm, implementing it and I finish with presenting my results and suggesting future work to get this into production. 
          
          python, pandas, numpy, matplotlib, scikit-learn, jupyter
      - layout: left
        title: CEITEC MU - Central European Institute of Technology
        link: https://www.ceitec.eu/rbp-bioinformatics/rg281
        # link_text: boringcompany.com
        sub_title: Research Specialist
        caption: September 2020 - Present
        quote: >
          Central European Institute of Technology is a young and dynamic center of scientific excellence, which strives to fulfill its mission in advancing knowledge in the field of life and materials sciences, based on the interconnection of the scientific capacities of its six partners.
        description: | # this will include new lines to allow paragraphs
          Working as a Research Specialist in Panagiotis Alexiou Research Group.

          The focus of the research performed in the lab is on ways that new technological breakthroughs in machine learning can be harnessed to produce novel biological meaning from sequencing data. Our expertise lies mainly in RNA/DNA Binding Protein regulation and function, and we utilize datasets based on the CLIP/ChIP-Seq family of methods.

          python, tersorflow, pytorch, fastai, deep learning, NLP, genomics
      - layout: left
        title: Oracle NetSuite
        link: https://www.netsuite.com/
        # link_text: boringcompany.com
        sub_title: Software Developer
        caption: July 2020 - September 2021
        quote: >
          NetSuite is the world’s leading provider of cloud-based business management software. NetSuite helps companies manage core business processes with a single, fully integrated system covering ERP/financials, CRM, ecommerce, inventory and more. NetSuite transforms how businesses operate so they can achieve their business vision.
        description: | # this will include new lines to allow paragraphs
          Working as a Software Developer in SuiteAnalytics Connect team.
          
          NetSuite SuiteAnalytics Connect Service provides the ability to archive, analyze and report on NetSuite data using a third-party tool or any custom-built application on any type of device.

          Java, SQL, ODBC, Perforce
      - layout: left
        title: Tieto
        link: https://www.tietoevry.com/
        # link_text: boringcompany.com
        sub_title: Software Developer
        caption: February 2018 - June 2020
        quote: >
          Tieto creates digital advantage for businesses and society. They are a leading digital services and software company with local presence and global capabilities.
        description: | # this will include new lines to allow paragraphs
          Working as a Software Developer in supporting team for developers and testers. Improving testing environment, developing testing framework and taking care of continous integration.

          Java, bash, python, Jenkins, TestNG, CI
      - layout: left
        title: Brno University of Technology
        link: https://www.fit.vut.cz/.en
        # link_text: boringcompany.com
        sub_title: Research Scholar
        caption: February 2016 - September 2018
        quote: >
          Faculty of Information Technology is in the position of one of the leading workplaces in the Czech Republic, which provides education and research in the field of information technology.
        description: | # this will include new lines to allow paragraphs
          Working on Corpora Processing Software project as part of [Knowledge Technology Research Group](https://www.fit.vut.cz/research/group/knot/.en).

          Java, Vaadin Framework, bash, python, HTML
#  - title: A Little More About Me
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#      - Rock climbing
#      - Gaming
#      - Knitting
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
#
#      Look at this cool image
#      ![Trees](/katarinagresova.github.io/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
